style(btn): btn gradient updated
tesla-safe/paz-app pull request #23
Opened 2021-07-31 17:08 UTC by Shaharyar-saleem

Gradient:
Btn background gradient => radial-gradient(circle, rgb(27 0 255) 13%, rgb(0 30 247 / 86%) 21%, rgb(107 90 234) 91%);
Btn on-hover gradient =>linear-gradient(to right, #12d3ff 0%, #921cff 103%);

Kindly let me know if we need to make changes in gradient shades.

2021-07-31 20:22 UTC, Shaharyar-saleem commented
if chainId != 56 then error screen is displaying

2021-07-31 20:25 UTC, Shaharyar-saleem commented
error msg needs to change as well

2021-08-01 21:35 UTC, bobachef commented on assets/js/connectWallet.js
> +    if (chainId != (56 || 97)) {
this is wrong.. 

And this proves to me that you didn't test your own code before telling me

2021-08-01 21:35 UTC, bobachef reviewed
Please test your code before you tell me to

2021-08-01 21:35 UTC, bobachef requested changes
please test your code and fix bugs before you ask me to take a look

2021-08-01 21:42 UTC, bobachef commented on assets/js/connectWallet.js
> +    if (chainId != (56 || 97)) {
this is simple javascript...

(56 || 97) evaluates to 56 

so you're not checking for 97

2021-08-03 16:04 UTC, Shaharyar-saleem commented
code has been tested.

2021-08-03 22:37 UTC, bobachef approved these changes
lgtm. Just open a new PR with the reload fix. Thank you.

2021-08-03 22:37 UTC, merged