fix(reload): working on dashboard reload bug
tesla-safe/paz-app pull request #25
Opened 2021-08-06 20:19 UTC by Shaharyar-saleem

working is in process getting following ERROR:
SyntaxError: Unexpected token o in JSON at position 1

2021-08-10 21:09 UTC, bobachef commented
> working is in process getting following ERROR:
> SyntaxError: Unexpected token o in JSON at position 1

is this still error that you're getting?

2021-08-11 10:48 UTC, Shaharyar-saleem commented
> > working is in process getting following ERROR:
> > SyntaxError: Unexpected token o in JSON at position 1
> 
> is this still error that you're getting?

No, i am not getting this error now.

2021-08-11 20:19 UTC, Shaharyar-saleem commented
@bobachef I need your help in the logout part

2021-08-12 13:15 UTC, Shaharyar-saleem commented on assets/js/connectWallet.js
> +    sessionStorage.clear();
done

2021-08-12 17:51 UTC, bobachef requested changes
Still way too many issues. Your testing should have found this. Please please please test your code before submitting this.

1. Disclaimer modal needs to open in center of view
2. Disclaimer needs both boxes checked and submitted before being able to proceed.
3. The connect button doesn't work properly and brings you to metamask site instead of the modal.
4. Please go through and find more bugs on your own.

2021-08-13 17:29 UTC, Shaharyar-saleem commented
> Still way too many issues. Your testing should have found this. Please please please test your code before submitting this.
> 
> 1. Disclaimer modal needs to open in center of view
> 2. Disclaimer needs both boxes checked and submitted before being able to proceed.
> 3. The connect button doesn't work properly and brings you to metamask site instead of the modal. This is probably because you have the modal opening automatically.
> 4. Please go through and find more bugs on your own.

All points followed

2021-08-13 19:29 UTC, bobachef approved these changes
lgtm

2021-08-13 19:29 UTC, merged