Webpack: work is in progress
tesla-safe/paz-app pull request #62
Opened 2021-11-19 18:01 UTC by Shaharyar-saleem

2021-11-20 16:23 UTC, bobachef commented on assets/js/blockchain/constants.js
> +const BUSD/**/ = {
remove this extra comment

2021-11-20 23:04 UTC, cchen408 commented on assets/js/blockchain/busdContract.js
> +let chainID;
`chainId` is the proper convention

2021-11-20 23:14 UTC, bobachef requested changes
some feedback

2021-11-20 23:14 UTC, bobachef commented on assets/js/blockchain/busdContract.js
> +let chainID;
`chainId` is the proper convention

2021-11-20 23:14 UTC, bobachef commented on assets/js/blockchain/connectWallet.js
>  const reinvestData = require('./reinvestContract');
this should be `reinvest`

2021-11-20 23:14 UTC, bobachef commented on assets/js/blockchain/connectWallet.js
>  const busdData = require('./busdContract');
this should be `busd`

2021-11-20 23:14 UTC, bobachef commented on assets/js/blockchain/connectWallet.js
> +const userData = require('./pazziveContract');
this should be `paz`

2021-11-20 23:14 UTC, bobachef commented on assets/js/blockchain/connectWallet.js
>  const trackerData = require('./dividendsTrackerContract');
this should be `tracker`

2021-11-20 23:14 UTC, bobachef commented on assets/js/blockchain/constants.js
> +let chainID = 56;
i don't think this belongs here.. especially if it's a `let`

2021-11-20 23:14 UTC, bobachef commented on assets/js/blockchain/constants.js
> +  return await signer.getChainId();
this doesn't belong here this should go in a helper or utility file

2021-11-20 23:14 UTC, bobachef commented on assets/js/blockchain/constants.js
> +async function getUserAddress(){
this doesn't belong here either.. the only thing that should be in here are constants.

2021-11-20 23:14 UTC, bobachef commented on assets/js/blockchain/reinvestContract.js
> +let chainID;
`chainId` is the convention

2021-11-20 23:14 UTC, bobachef commented on assets/js/blockchain/pazziveContract.js
>  const LIVE_CONTRACT = "0xb9f5C03d733C9F7eBA6B81c48A55ef0bEBBB200A";
all of these should be constants and should just be referenced from there

2021-11-23 10:27 UTC, Shaharyar-saleem commented on assets/js/blockchain/constants.js
> +const BUSD/**/ = {
removed

2021-11-23 10:29 UTC, Shaharyar-saleem commented on assets/js/blockchain/busdContract.js
> +let chainID;
followed

2021-11-23 10:34 UTC, Shaharyar-saleem commented on assets/js/blockchain/connectWallet.js
>  const reinvestData = require('./reinvestContract');
followed

2021-11-23 10:35 UTC, Shaharyar-saleem commented on assets/js/blockchain/connectWallet.js
>  const trackerData = require('./dividendsTrackerContract');
followed

2021-11-23 17:55 UTC, bobachef commented on assets/js/blockchain/busdContract.js
> +}
this is a bit redundant imo what we can always try is

```
const signer = constants.signer;
const {getChainId, getAddress:getUserAddress} = signer; 

await getChainId()
await getUserAddress()

```

this is called object destructuring.

2021-11-24 10:24 UTC, Shaharyar-saleem commented on assets/js/blockchain/busdContract.js
> +}
done

2021-11-25 17:27 UTC, bobachef approved these changes
lgtm

2021-11-25 17:27 UTC, merged